version: '3'

tasks:
  build:
    cmds:
      - mkdir -p bin
      - go build -o bin/alias-server .

  run:
    cmds:
      - go run . config.local.json

  test:
    cmds:
      - go test ./...

  clean:
    cmds:
      - rm -rf bin
