version: '3'

tasks:
  build:
    cmds:
      - mkdir -p bin
      - go build -o bin/alias-server ./cmd/alias-server

  run:
    cmds:
      - go run ./cmd/alias-server config.local.json

  format:
    cmds:
      - gofmt -w cmd/alias-server/*.go

  test:
    cmds:
      - go test ./...

  clean:
    cmds:
      - rm -rf bin
